# Generated by Django 2.1 on 2018-08-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cquser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_token',
            name='req10_1',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='user_token',
            name='req1_1',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='user_token',
            name='req2_1',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='user_token',
            name='req3_1',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='user_token',
            name='req4_1',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='user_token',
            name='req5_1',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='user_token',
            name='req6_1',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='user_token',
            name='req7_1',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='user_token',
            name='req8_1',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='user_token',
            name='req9_1',
            field=models.FloatField(default=None),
        ),
    ]
