# Generated by Django 2.1 on 2018-08-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cquser', '0002_auto_20180811_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_token',
            old_name='req10_1',
            new_name='req10_a',
        ),
        migrations.RenameField(
            model_name='user_token',
            old_name='req1_1',
            new_name='req1_a',
        ),
        migrations.RenameField(
            model_name='user_token',
            old_name='req2_1',
            new_name='req2_a',
        ),
        migrations.RenameField(
            model_name='user_token',
            old_name='req3_1',
            new_name='req3_a',
        ),
        migrations.RenameField(
            model_name='user_token',
            old_name='req4_1',
            new_name='req4_a',
        ),
        migrations.RenameField(
            model_name='user_token',
            old_name='req5_1',
            new_name='req5_a',
        ),
        migrations.RenameField(
            model_name='user_token',
            old_name='req6_1',
            new_name='req6_a',
        ),
        migrations.RenameField(
            model_name='user_token',
            old_name='req7_1',
            new_name='req7_a',
        ),
        migrations.RenameField(
            model_name='user_token',
            old_name='req8_1',
            new_name='req8_a',
        ),
        migrations.RenameField(
            model_name='user_token',
            old_name='req9_1',
            new_name='req9_a',
        ),
        migrations.AddField(
            model_name='transactionm',
            name='coinamt',
            field=models.FloatField(default=None),
        ),
    ]
