# Generated by Django 2.0.7 on 2018-07-27 00:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cquser', '0002_auto_20180722_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=80)),
                ('refresh_token', models.CharField(max_length=80)),
                ('user', models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
