# Generated by Django 2.0.7 on 2018-07-27 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cquser', '0003_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_token',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
