# Generated by Django 2.0.7 on 2018-08-19 00:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='spot_price',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('btc', models.FloatField(default=None)),
                ('bch', models.FloatField(default=None)),
                ('eth', models.FloatField(default=None)),
                ('ltc', models.FloatField(default=None)),
                ('etc', models.FloatField(default=None)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
