# Generated by Django 2.0.7 on 2018-07-29 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBtoken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.FloatField()),
                ('refresh_token', models.FloatField()),
                ('eth', models.FloatField()),
                ('ltc', models.FloatField()),
                ('dt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.buy_price')),
            ],
        ),
    ]
