# Generated by Django 2.0.7 on 2018-07-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_cbtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbtoken',
            name='dt',
        ),
        migrations.RemoveField(
            model_name='cbtoken',
            name='eth',
        ),
        migrations.RemoveField(
            model_name='cbtoken',
            name='ltc',
        ),
        migrations.AlterField(
            model_name='cbtoken',
            name='access_token',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='cbtoken',
            name='refresh_token',
            field=models.CharField(max_length=80),
        ),
    ]
