# Generated by Django 2.0.7 on 2018-07-29 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20180729_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbtoken',
            name='access_token',
        ),
    ]
