# Generated by Django 2.0.7 on 2018-07-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_remove_cbtoken_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtoken',
            name='access_token',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AlterField(
            model_name='cbtoken',
            name='refresh_token',
            field=models.CharField(default=0, max_length=80),
        ),
    ]
